### ISSUE TITLE
Cannot append 'title' element to selection

### ISSUE THREAD

**Issue by Arrow7000** [Olical/react-faux-dom#104]
Firstly thank you for creating react-faux-dom! Without this I would have no way of building complex D3 charts in apps with complex state. 

I am trying to build a heatmap chart based on http://bl.ocks.org/tjdecke/5558084. 

It mostly works, except for two things, the tooltip and the legend. I've removed the legend code for now, but the tooltip still isn't working and I can't work out why. I've looked at other issues in this repo to see if I've made a mistake, but I can't see anything glaringly wrong in my code.

I'll paste the full component code below, but it seems to be these two lines that doesn't work:

```
cards.append("title");
...
cards.select("title").text(function (d) { return d.value; });
```

Whereas the DOM in the original block looks like this:

![image](https://user-images.githubusercontent.com/13225609/26925434-b1a00b04-4c41-11e7-95a1-5c047cf12900.png)

Mine looks like this: 

![image](https://user-images.githubusercontent.com/13225609/26925469-d1b5c3a2-4c41-11e7-8767-ece19350c2ef.png)

I.e. it never gets the `title` element appended to it.

---
I've pasted my full component code in case it helps:

```
class HeatMap extends Component {
    render() {

        const div = new ReactFauxDOM.Element('div');

        const { rows } = this.props;

        if (!rows || !rows.length) {
            return null;
        }

        const margin = { top: 50, right: 0, bottom: 100, left: 30 };
        const width = 960 - margin.left - margin.right;
        const height = 430 - margin.top - margin.bottom;
        const gridSize = Math.floor(width / 24);
        const days = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"];
        const times = ["12a", "1a", "2a", "3a", "4a", "5a", "6a", "7a", "8a", "9a", "10a", "11a", "12p", "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p", "10p", "11p"];


        var svg = d3.select(div).append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        var dayLabels = svg.selectAll(".dayLabel")
            .data(days)
            .enter().append("text")
            .text(function (d) { return d; })
            .attr("x", 0)
            .attr("y", function (d, i) { return i * gridSize; })
            .style("text-anchor", "end")
            .attr("transform", "translate(-6," + gridSize / 1.5 + ")")
            .attr("class", function (d, i) { return ((i >= 0 && i <= 4) ? "dayLabel mono axis axis-workweek" : "dayLabel mono axis"); });

        var timeLabels = svg.selectAll(".timeLabel")
            .data(times)
            .enter().append("text")
            .text(function (d) { return d; })
            .attr("x", function (d, i) { return i * gridSize; })
            .attr("y", 0)
            .style("text-anchor", "middle")
            .attr("transform", "translate(" + gridSize / 2 + ", -6)")
            .attr("class", function (d, i) { return ((i >= 7 && i <= 16) ? "timeLabel mono axis axis-worktime" : "timeLabel mono axis"); });

        const data = map(rows, (row) => ({
            hour: +row[0],
            day: +row[1],
            value: +row[2]
        }));

        var scale = d3.scaleLinear()
            .domain([0, d3.max(data, d => d.value)])
            .range([0, 1]);

        var cards = svg.selectAll(".hour")
            .data(data, function (d) { return d.day + ':' + d.hour; });

        cards.append("title"); // title never seems to actually get appended to the cards

        cards.enter().append("rect")
            .attr("x", function (d) { return (d.hour) * gridSize; })
            .attr("y", function (d) { return (d.day) * gridSize; })
            .attr("rx", 4)
            .attr("ry", 4)
            .attr("class", "hour bordered")
            .attr("width", gridSize)
            .attr("height", gridSize)
            .style("fill", d => d3Chrom.interpolateRdYlGn(scale(d.value)));

        cards.select("title").text(function (d) { return d.value; });

        cards.exit().remove();

        return div.toReact();
    }
}
```

**Comment by Arrow7000** [comment]
FYI if pointed in the right direction I'd be more than happy to try and solve this issue myself in a pull request :smiley:

**Comment by tibotiber** [comment]
Hi @Arrow7000, which version of D3 are you using?

**Comment by tibotiber** [comment]
Oh, I see a `d3.scaleLinear` so it should be d3 v4. I think your issue is that in d3 v3
```js
var cards = svg.selectAll(".hour")
  .data(data, function (d) { return d.day + ':' + d.hour; });
cards.append("title");
```
would perform the append on the enter+update selection, while in d3 v4 it does it for the update selection only. I have run into similar issues when upgrading to d3 v4.

To perform the append on the enter selection you should move the append after `.enter()`.
```js
var cards = svg.selectAll(".hour")
  .data(data, function (d) { return d.day + ':' + d.hour; });
cards.enter()
  .append("title")
  .append("rect")
```
 and if you want to perform it on the enter+update selection, you need to use `.merge(cards)` at the end of your enter group before you append the title.

Hope this helps you :)

**Comment by Arrow7000** [comment]
Thanks @tibotiber, that does seem to work! I'm still pretty new to D3 so good to know what to look out for when copying other v3 examples.

Thanks :)

**Comment by Arrow7000** [comment]
Btw is there an article or blog post you could point me to that explains the differences between v3 and v4 in more detail?

**Comment by tibotiber** [comment]
@Arrow7000 https://github.com/d3/d3/blob/master/CHANGES.md is pretty complete, although I can't recall reading about the changes in selectors logic. I had to debug some of my code to understand there was some changes, and then I stumbled upon a v4 example of the enter-update-exit pattern that had good explanations in the comments. So basically, sorry, no magic link 😉
