### ISSUE TITLE
d3 canvas in server rendering?

### ISSUE THREAD

**Issue by orkun** [Olical/react-faux-dom#107]
Hi,
Is it possible to use it with d3 canvas in server rendering?

Regards

**Comment by Olical** [comment]
No, this would require full simulation of a canvas element. If you can find a server side canvas somewhere, maybe you can use that. Or just use SVG?

**Comment by Olical** [comment]
I'm going to close this since it's outside the scope of this project really. Maybe someone who has done canvas server side could work out how to combine these two concepts?
