### ISSUE TITLE
documentation.md no examples folder

### ISSUE THREAD

**Issue by RShergold** [Olical/react-faux-dom#109]
'To see it in action, check out the animate-d3-with-hoc and update-d3-with-hoc mini-apps in the examples folder.'

Example folder does not exist.

**Comment by tibotiber** [comment]
Thanks for reporting @RShergold. Opened a PR to fix this and point to the new examples location.

**Comment by Olical** [comment]
Good catch, thanks for the report and prompt fix! :tada:
