### ISSUE TITLE
support for MutationObserver

### ISSUE THREAD

**Issue by graingert** [Olical/react-faux-dom#111]
would be handy for animations etc.

**Comment by Olical** [comment]
I'm afraid I don't know how this would help, I've never used MutationObserver.

The library is designed to provide a simple mutable DOM that you can render to a React DOM when required, which it does. I'm reluctant to add anything else or change it unless it's for a really good reason that would help a lot of people.

I've always stated that it's not ideal for animations since D3 does some funky stuff with timers that makes it hard to work with inside stateless React. Maybe that's okay 😃

**Comment by graingert** [comment]
@Olical what about just an event whenever the dom mutates?

**Comment by graingert** [comment]
really I'm looking to make an interface that's
```js
function d3JSXStream(data$: Observable<T>, draw: (fd: FauxDom, data: T) => any): Observable<JSX> { ... }
```

**Comment by Olical** [comment]
RFD doesn't have access to these things though, at least, I don't think it does. It's literally a recursive data structure of "faux" DOM nodes with a method that walks the tree and turns it into React. Surely if you want to add mutation observers, that can be done outside? Maybe I'm mistaken, I haven't dealt in this space for a while. I don't even write JavaScript anymore 😅

**Comment by graingert** [comment]
hmm it looks like to do this, it will either require Proxy or descriptors for every possible dom attribute and style attribute

**Comment by Olical** [comment]
If you need to do something funky, you can always just drop out of the React render tree into normal mutable DOM for that one D3 component. It's what I've always recommended when someone is trying to do something with lots of animation and physics etc.

This doesn't sound like a trivial change, which is something I'm trying to avoid.

**Comment by Olical** [comment]
This is a great post on the subject http://nicolashery.com/integrating-d3js-visualizations-in-a-react-app/

**Comment by graingert** [comment]
@Olical actually it might be fairly easy.... do you support DOM attributes like:

```js
const img = rfd.createElement('img');
img.src = "https://example.com/maymay.jpg";
```

**Comment by Olical** [comment]
Nope, only within style since D3 always uses the correct methods to alter attributes.

**Comment by graingert** [comment]
@Olical ah ok. It's possible to add descriptors to every CSSStyleDeclaration property.

**Comment by Olical** [comment]
Huh, I guess you mean TypeScript descriptors? I've never used TypeScript and only dabbled with Flow.

I'd still recommend that you have a read through the post I linked and potentially roll your own outside of ReactFauxDOM. I'd say it's great for simple stateless problems, but gets uncertain for anything more complex.

**Comment by graingert** [comment]
@Olical no I mean getters and setters.

**Comment by Olical** [comment]
I'd rather not maintain a list of individual getters and setters. Web standards have a tendency to evolve unceasingly. I would like this library to stay minimal and generic.

I'm totally open to a more type friendly fork and would link to it if you wanted to change those things for yourself though. I don't use any typed JavaScript (or even any JavaScript) right now, so I wouldn't feel confident making those changes for you and hoping they're correct.

**Comment by Olical** [comment]
I'm going to close this issue _for now_. I'm not sure what needs to change and I'm reluctant to make changes unless they are absolutely necessary. If you'd like to submit a PR then I'll give it some thought 🙂

I just don't want to leave this sitting here open when I don't really intend to do anything with it. I hope that's okay.
