### ISSUE TITLE
Change bar chart hover color?

### ISSUE THREAD

**Issue by Xeoncross** [Olical/react-faux-dom#112]
I tried looking at `<BarChart />`, [`<Bar />`](https://github.com/recharts/recharts/blob/master/src/cartesian/Bar.js), and `<ResponsiveContainer />` but I don't see any option for changing the default `<Bar />` hover from gray (`fill: #ccc`) to another color.

![gray bar](https://user-images.githubusercontent.com/56460/30000728-07303d9e-903c-11e7-871a-ca40821189ee.png)

**Comment by Olical** [comment]
You should probably ask this on the repository of the chart library, this library doesn't do much other than convert fake DOM trees into React elements.

You could probably just use CSS if the component doesn't give you an option though.

**Comment by Xeoncross** [comment]
I'm sorry, It was late and I posted on the wrong tab. Thank you!

**Comment by Olical** [comment]
No problem! I assumed it might've been something like that 😄
