### ISSUE TITLE
npm ERR! peerinvalid Peer react-faux-dom@1.1.0 wants react@0.x

### ISSUE THREAD

**Issue by Theadd** [Olical/react-faux-dom#12]
[package.json#L44](https://github.com/Olical/react-faux-dom/blob/master/package.json#L44)

```
  "peerDependencies": {
    "react": "0.x"
  }
```

This doesn't match with `0.14.0-rc1` since npm doesn't versions containing [a-Z] characters as releases. (as long as I can remember)

```
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-pure-render-mixin@0.14.0-rc1 wants react@^0.14.0-rc1
npm ERR! peerinvalid Peer react-mirror@0.4.1 wants react@>=0.13.3 || ^0.14.0-beta3 || ^0.14.0-rc1
npm ERR! peerinvalid Peer redbox-react@1.0.5 wants react@>=0.13.2 || ^0.14.0-rc1
npm ERR! peerinvalid Peer react-faux-dom@1.1.0 wants react@0.x
```

**Comment by kidwm** [comment]
@Olical why not just change to "^0.14.0"?
https://github.com/rackt/react-router/issues/2194

**Comment by Olical** [comment]
Because then the moment 0.15 comes out we have the same issue again. I
don't depend on the React API too heavily, we should be able to use 12, 13,
14 and later. I don't see why * would be a problem for now.

**Comment by kidwm** [comment]
@Olical But maybe one day you will use some newer React API, or do this when it occurs.

**Comment by Olical** [comment]
I'm going to change this to use `*` for now because new versions will forever have this issue. If we find a version that's incompatible then I'll deal with that as it arises. But that's far less likely.
