### ISSUE TITLE
Is it possible to get the stringified DOM?

### ISSUE THREAD

**Issue by iainbryson** [Olical/react-faux-dom#127]
Hi there,

Thanks for the marvelous library!  One question: I'm looking at a use-case involving SSR of _images_ from d3.js charts.  The design I'd intended was to generate an SVG document via react-faux-dom (or jsdom), then render the svg to PNG/JPG etc...

Is react-faux-dom supposed to generate a full DOM string in `innerHTML` for all the children?  It doesn't seem to and the code looks like it spits out just the `textContent`, not the child-hierarchy, though I haven't read deeply.  Is there any way to accomplish this using the library?

Regards,
— Iain

**Comment by Olical** [comment]
Hey! I hope you're finding it useful :smile: 

As far as I know, you will just use RFD to generate a React tree (with `.toReact()`), then you would use your normal SSR techniques to turn your React tree into HTML. I don't think there's anything super special about it?

Have you tried it and encountered issues then? Or just curious at the moment? I have a feeling it'll Just Work<sup>TM</sup>.

**Comment by iainbryson** [comment]
Great, that worked.  To recap:

```
el.innerHTML
```

Returns an empty string, but 

```
renderToString(el.toReact())
```

Returns the elements as strings (in my case, an SVG document of a chart created in D3).

Thanks!

**Comment by Olical** [comment]
Glad it all worked out for you :smile:
