### ISSUE TITLE
Limitations 

### ISSUE THREAD

**Issue by bumbeishvili** [Olical/react-faux-dom#131]
Please include limitations inside readme.md file so the newcomers will not stay frustrated when decide to use these features
Like 
1. Zooming
2. Dragging
3. Brushing
e.t.c

**Comment by Olical** [comment]
I guess this could be useful. The example does mention the fact that it doesn't support anything like animations or anything that mutates the DOM. The mixin tool that was contributed only adds support for some animations too.

I guess it would be nice if the limitations were clearer though.

**Comment by bumbeishvili** [comment]
Yes, I agree, when I started using react-faux-dom, I had impression that I could do everything, which d3 has done including dragging & zooming & brushing
