### ISSUE TITLE
Expose component propTypes and defaultProps.

### ISSUE THREAD

**Issue by royipressburger** [Olical/react-faux-dom#138]
Hi,

This is not a bug but a feature request :).

In react when you create a component:
```js
class MyComponent extends Component {
    // component code
}

MyComponent.propTypes = { //some props }
MyComponent.defaultProps = { //the defaults }

export default MyComponent;
```

Then from some other component you can have access to the component props and default props like so:
```js
import MyComponent from './MyComponent'

// here I can access the component props and default props:
console.log(MyComponent.propTypes);
console.log(MyComponent.defaultProps);
```

But if I wrap `MyComponent` with `WithFauxDom` then the case above is no longer working.

I manage to expose `propTypes` by adding this line:
`WithFauxDOM.propTypes = WrappedComponent.propTypes`
in [_withFauxDom.js line 62](https://github.com/Olical/react-faux-dom/blob/master/lib/_withFauxDOM.js#L62)

However this case didn't work for the `defaultProps`
Can you think of a way to expose the defaults?

My use case is:
I have a project with a lot of small components.
I have a page that generate for each component all the props and default props and how to render this component (this is like docs from components)

Thanks ahead

**Comment by Olical** [comment]
I'm afraid I'm not actively adding features to this project at the moment and I've never really worked with the higher order component at all. I only wrote the initial static core that handles simple, non animated things.

I'm not sure how you'd go about getting it working for `defaultProps` either I'm afraid, I've been away from JavaScript and React for a long time now. If you want to give it a go I'll be happy to review a PR, if not I don't think this'll be happening any time soon I'm afraid :disappointed:

**Comment by Olical** [comment]
I'm going to close this for now since it's more of a feature than a bug and I don't really have the time or motivation to add new features right now. If you want to submit it as a PR I'll be more than happy to work with you on getting it merged and released though! I hope you're having a nice weekend!
