### ISSUE TITLE
d3.select(...).clone() report error

### ISSUE THREAD

**Issue by xiechao06** [Olical/react-faux-dom#142]
I've come into errors in the following codes: 

```javascript
d3.select(faux)
	.append('div')
	.html('hello')
	.clone()
	.html('world')
```

and an error `this.cloneNode is not a function` is reported, hope faux-dom could support dom method `cloneNode`. 

please check this [sandbox](https://codesandbox.io/s/j3m4zyqvyw) for detail

**Comment by Olical** [comment]
Shouldn't be too difficult to implement? If you'd like to submit a PR I'll happily take a look at it at some point soon.

If not I may get around to implementing it eventually but I'm quite busy at the moment I'm afraid.

Thanks for the report though!

**Comment by Olical** [comment]
Should be fixed by your cloning PR, thank you very much!
