### ISSUE TITLE
consider copy static properties to withFauxDOM HOC?

### ISSUE THREAD

**Issue by xiechao06** [Olical/react-faux-dom#144]
```javascript
class MyChart extends Component {
	...
}

MyChart.constants = {...}
export default withFauxDOM(MyChart)

// in some other files
import MyChart from './MyChart'

console.log(MyChart.constants) // missing?

```
btw, there's a package https://www.npmjs.com/package/hoist-non-react-statics, do you need a pull request?

**Comment by Olical** [comment]
It seems to make sense to me, but I'm not really using this project any more. I don't write JavaScript and only use React through ClojureScript these days. If it would help you and you'd like to submit it as a pull request I'll gladly take a look. If you don't _need_ it though, let's leave it out. I'd rather not change this project any more if I can avoid it. Other than fixing bugs, of course.
