### ISSUE TITLE
componentWillMount deprecation

### ISSUE THREAD

**Issue by jlucier** [Olical/react-faux-dom#150]
I'm using this library with the `WithFauxDom` HOC, and getting deprecation warnings about internal usage of `componentWillMount` from React.

Is there any plan to make this library compliant with React >= 17.x.x with regards to this lifecycle method?

**Comment by Olical** [comment]
I have no plans to touch this project at the moment I'm afraid. I have no idea what the migration path would be (hooks?), I haven't been involved with React or JavaScript for a good few years now.

If you think you know what needs to be done I'd be happy to incorporate changes and release them. Thanks for the heads up and report though!

**Comment by jlucier** [comment]
I hesitate to say it without diving deeper into the internals of the library... but it might be as simple as find/replace `componentWillMount` with `componentDidMount`.

If you've been out of the React loop for a while, the React people found that lots of people were using the lifecycle methods to do things that they didn't intend to officially support or deemed them to be anti-patterns. Things like using the function `componentWillReceiveProps` to update derived state within components. The problem is the lifecycle methods that have `Will` in the name might get called by the React internals many times during an update, so anything you put in there is not actually executing as you intend. As such, they want people moving away from using those methods.

If this library really only uses `componentWillMount` specifically, I think it will just work to change over to `componentDidMount`. If you had been using `componentWillReceiveProps` or something, that would be a more involved migration because the new method to use, `componentDidUpdate`, is functionally pretty different.

**Comment by tibotiber** [comment]
Hi @jlucier, I've checked and there is a single relevant call to `componentWillMount`, which could very well be replaced by `componentDidMount` as it sets up some variables, nothing more. I'm willing to test / review a PR if you or anyone else would get it opened.

Looking further than this tiny patch to get rid of the warning. I think it would be interesting for an active user of the lib (which neither @Olical nor me are anymore) to attempt refactoring the HOC to use hooks. It should be feasible without understanding the internals of the faux dom. I can assist if someone takes the lead on this. :)

**Comment by Olical** [comment]
I'm afraid I won't ever get around to changing this, I don't _think_ anyone is worried about this anymore anyway? I'm basically deprecating this library since there's probably better ways to do it and I'm 100% out of context now. I haven't touched React or JavaScript for so long now.

I'm going to archive this repo and close this issue. If anyone wants to take these ideas forward please feel free to fork it, if you want to carry it on in a spiritual successor sort of way I'm more than happy to link to your efforts from the readme.

Thanks for the wild ride on this project :smile:
