### ISSUE TITLE
state, render and d3

### ISSUE THREAD

**Issue by KeitIG** [Olical/react-faux-dom#18]
Hey !

I had just a 'under the hood' question, imagine I have a state `{ width: 100 }` that I apply to my d3 svg container to define its width. When the state `width` is updated, is the full svg redrawed or is just the attribute `width` updated ?

**Comment by Olical** [comment]
Just the width, that's React doing it's thing. I mean, it should just be the width because of the DOM reconciliation. If it's not there's a bug! And a big one at that.

**Comment by Olical** [comment]
I mean, the entire SVG is rebuilt in memory, but only the width is updated in the actual DOM. That's just how React works. It's up to you to split your application up in such a way that not everything is re-rendered on every change. That's what shouldComponentUpdate is for though.

**Comment by KeitIG** [comment]
Yep, but the width attribute is set "the d3 way". Take that example:

```
import React, { Component } from 'react';
import d3 from 'd3';
import ReactFauxDOM from 'react-faux-dom';

import worldMapData from '../../constants/world-110m2.js';
import topojson from 'topojson';


export default class Strategy extends Component {

    constructor(props) {

        super(props);
        this.state = {
            width: 0
        };
    }

    render() {

        var width = this.state.width,
            height = this.state.width / 2;

        var projection = d3.geo.mercator()
            .scale((width + 1) / 2 / Math.PI)
            .translate([width / 2, height / 1.6])
            .precision(.1);

        var svg = d3.select(ReactFauxDOM.createElement('div')).append("svg")
            .attr("width", width) // THERE: how is the svg here ?
            .attr("height", height);

        var path = d3.geo.path()
            .projection(projection);

        var g = svg.append("g");

        var topology = worldMapData;

        g.selectAll("path")
            .data(topojson.feature(topology, topology.objects.countries).features)
            .enter()
                .append("path")
                .attr("d", path)

        var svgToReact = svg.node().toReact();

        return(
            <div className='strategy-map' ref='mapContainer'>
                <h3>World Map</h3>
                <div className='map strategy-world-map' ref='map'>
                    { svgToReact }
                </div>
            </div>
        );
    }

    handleResize() {
        this.setState({ width : this.refs.mapContainer.offsetWidth });
    }

    componentDidMount() {
        this.handleResize(this);
        window.addEventListener('resize', this.handleResize.bind(this));
    }

    componentWillUnmount() {
        window.removeEventListener('resize', this.handleResize.bind(this));
    }
}
```

**Comment by Olical** [comment]
That looks fine to me, but shouldn't you be using `setState` in the constructor too? `.attr(...)` still binds through to React properties, so the DOM reconciliation should still work it out. Why, are you experiencing a complete re-render of the DOM every time?

If you have the inspector open you should see only the width attribute flash as you resize the window.

**Comment by KeitIG** [comment]
Mmmmh it looks like all the path are redrawing, I'm doing a few more test to check that.

**Comment by KeitIG** [comment]
A few things to say:
- Yes it is redrawing, but it was due to the fact I change the projection with the width state. 
- After setting flat values for `projection`, the `<path>` are not redrawing and only the `with` attribute is updated when the window is resized
- So everything works as expected !

thanks a lot

**Comment by Olical** [comment]
Ah, I see. Well I'm glad it's working as expected! :D
