### ISSUE TITLE
slider using react-faux-dom.

### ISSUE THREAD

**Issue by vikrammirla** [Olical/react-faux-dom#20]
Hi,
I am trying to add slider using react-faux-dom.
As I am absolute beginner with react, I am not sure what to do in handleDrag() function.
Any suggestions on updating values after a slider is dragged?
Thank you

```javascript
import d3 from 'd3'
import React from 'react'
import ReactFauxDOM from 'react-faux-dom'

class Slider extends React.Component {
  componentDidMount() {
    var drag = d3.behavior.drag()
      .on("drag", this.handleDrag)
    var dom = React.findDOMNode(this);
    d3.select(dom).call(drag)
  }

  handleDrag() {
    var posY = d3.mouse(React.findDOMNode(this)),
      newValue = Math.max(0, Math.min(1,posY/400))
    //this.onChange(newValue);
    //not sure what to do here
    //need advice
  }

  render() {
    const {width, height, value} = this.props
    const el = d3.select(ReactFauxDOM.createElement('svg'))
      .attr('width',width)
      .attr('height',height)

    el.append("rect")
      .attr('width',width*value)
      .attr('height',height)
      .attr('class',"Slider-fill")

    el.append("rect")
      .attr('width',width)
      .attr('height',height)
      .attr('class',"Slider-border")

    el.append("text")
      .attr('x',width/2)
      .attr('y',height/2)
      .text(value)

    return el.node().toReact();
  }
}

export default Slider
```

**Comment by Olical** [comment]
Hey Vikram,

You're most of the way there but it looks like you're just adding your listener in the wrong place. You don't need to use `componentDidMount` with this library. I also formatted your code a little just so it's easier to read on GitHub.

I'm not an expert with D3 I'm afraid, and I've never dealt with dragging. There should be no reason why it shouldn't work though, all you need to do is move your event listener into the render function (it won't add a new listener every time, don't worry).

**Comment by vikrammirla** [comment]
Thanks for your response. I will try your suggestion

**Comment by Olical** [comment]
I'm afraid I'm going to close this (among other issues), the reason is stated in the new [limitations section](https://github.com/Olical/react-faux-dom#limitations) in the readme (PR #30). This is essentially a question of state management which is [illustrated in my lab](http://lab.oli.me.uk/react-faux-dom-state/) with a simple example. The principal is essentially the same though!

**Comment by vikrammirla** [comment]
Thanks for the example Oliver.
