### ISSUE TITLE
Support for zoom

### ISSUE THREAD

**Issue by KeitIG** [Olical/react-faux-dom#21]
Hey, 

another task on your list when you'll get time: http://bl.ocks.org/mbostock/8fadc5ac9c2a9e7c5ba2

basically:
```javascript
var zoom = d3.behavior.zoom()
    .scaleExtent([1, 8])
    .on("zoom", zoomed);
```

**Comment by Olical** [comment]
Looks like a fun challenge :)

**Comment by Olical** [comment]
I'm afraid I'm going to close this (among other issues), the reason is stated in the new [limitations section](https://github.com/Olical/react-faux-dom#limitations) in the readme (PR #30). This is essentially a question of state management which is [illustrated in my lab](http://lab.oli.me.uk/react-faux-dom-state/) with a simple example. The principal is essentially the same though!

**Comment by adityap86** [comment]
Hey Can you suggest  a way to introduce the zoom in feature and still keep the react-faux-dom in the code?

**Comment by KeitIG** [comment]
@adityap86 You can't. Or you have to draw your svg with react-faux-dom, then use `componentDidMount` and add your d3.js zoom behavior here.

**Comment by adityap86** [comment]
Hey @KeitIG , Thanks for the reply. I tried something like this (But its not working, do i have to add zoom like in the regular fashion also inside the render function with the d3 component) : 
```
componentDidMount() {
    if (this.props.width === '100%') {
        window.addEventListener(''scroll'', this.zoomed);
    }
    this.zoomed();
  }
zoomed() {
        lChart.select(".x.axis").call(hAxis);
        lChart.select(".y.axis").call(vAxis);
        lChart.select(".x.axis.major").call(majorAxis);
        lChart.select(".line")
              .attr("class", "line")
              .attr("d", line);
   }
```

**Comment by KeitIG** [comment]
For zoom behavior, use d3 internal one. I didn't test my code, but it should be someting like:

componentDidMount() {

var svg = d3.select("svg")
    .call(d3.behavior.zoom()
        .on("zoom", function () {
            svg.attr("transform", "translate(" + d3.event.translate + ")" + " scale(" + d3.event.scale + ")")
        })
    );
}

Of course, you could do that with states instead of updating attributes directly, it's up to you.
For the rest, you should find everything you need in d3 docs and on bl.ocks.org

**Comment by adityap86** [comment]
I have a working code of what i want in this [jsfiddle link]( https://jsfiddle.net/adityap16/x78zgwux/18/). So currently i am using this code and porting it into "render function" and then just passing it node.toReact(). if you can explain on how to port this code correctly that would be really helpful. I am quiet new to both d3.js and react.js . So kind of lost here

**Comment by KeitIG** [comment]
Ok, for that kind of d3.js work, I don't recomment you to use `react-faux-dom`. `react-faux-dom` is really great for small svg without interactions, but not for what you're looking for.

Here's what I would do:

``` javascript
import React, { Component } from 'react';

export default class MySVG extends Component {

    constructor(props) {

        super(props);
        this.state = {}
    }

    render() {

        return (
            <div id="svg-container"></svg>
        );
    }

    componentDidMount() {

        // All your d3 code
        
        var myChart = d3.select('#svg-container').append('svg') // ... (line 133)

        // ...
    }
}

```

**Comment by adityap86** [comment]
@KeitIG  Thanks !! . So it kind of worked but not completely. My axis and legend are coming up but not line's.
