### ISSUE TITLE
support Element.childNodes, Element.hasAttribute(name)

### ISSUE THREAD

**Issue by sherdeadlock** [Olical/react-faux-dom#28]
* http://devdocs.io/dom/childnode
* https://github.com/ScottLogic/d3fc/blob/master/src/layout/layout.js

d3fc.layout iterate DOM by childNodes. Thanks.

```js
// creates the structure required by the layout engine
function createNodes(el) {
    function getChildNodes() {
        var children = [];
        for (var i = 0; i < el.childNodes.length; i++) {
            var child = el.childNodes[i];
            if (child.nodeType === 1) {
                if (child.getAttribute('layout-style')) {
                    children.push(createNodes(child));
                }
            }
        }
        return children;
    }
    return {
        style: parseStyle(el.getAttribute('layout-style')),
        children: getChildNodes(el),
        element: el
    };
}
```

**Comment by sherdeadlock** [comment]
There is an example https://github.com/sherdeadlock/react-fc

* add Element.hasAttribute
* iterate DOM by Element.children

And d3fc.layout try to get width and height from element style. 
I don't known how to fix it.
https://github.com/sherdeadlock/react-fc/blob/master/src/layout.js#L108

Thanks.

**Comment by Olical** [comment]
Iterating children is easy, we can add that, so is `hasAttribute`. I don't think there's any way to measure the width though, that requires the element to be in the DOM and actually rendered, when you're using `react-faux-dom` you're simply using an object, not a DOM element with a real width. Any measurements would probably be a little hacky and will not work if you used a stylesheet to set the width.

**Comment by Olical** [comment]
@sherdeadlock As pointed out here, you can probably measure things using the component lifecycle hooks https://github.com/Olical/react-faux-dom/pull/30#issuecomment-155933590 I'm not sure if that helps though.

**Comment by sherdeadlock** [comment]
Thanks. I find out that d3fc.layout can initialize root measurements. wroks~
```
selection.layout(width, height);
```

**Comment by Olical** [comment]
Oh cool! So have you managed to get it working? The main thing you need to
do is make sure you're managing any state within React correctly.

**Comment by sherdeadlock** [comment]
I just give it an initial props.
https://github.com/sherdeadlock/react-fc/blob/master/src/index.js#L37

It's possible to get measurements from parent node.
I will give it a try.

**Comment by Olical** [comment]
You could setInitialState to an estimate, then on the first componentDidMount actually measure it and update the state.

**Comment by Olical** [comment]
@sergi has added childNodes in #35, does that fix the majority of this issue? Or is `hasAttribute` essential too? `childNodes` is out in `v2.2.0`.

**Comment by kidwm** [comment]
@Olical Hey, you forgot to update the changelog for `v2.2.0`

**Comment by Olical** [comment]
Ah, my bad! I'll fix it. Thank you for letting me know.

**Comment by Olical** [comment]
@kidwm Change log is fixed.

@sherdeadlock Do you mind if I close this? We could create another, more specific, issue if required. I think half of this is solved now, arguably the more important half too.

**Comment by sherdeadlock** [comment]
Ok. Thanks. :D
