### ISSUE TITLE
changing fill color on 'mouseover' and 'mouseout'?

### ISSUE THREAD

**Issue by akash5474** [Olical/react-faux-dom#29]
Hi there, thanks for creating this great package.  I was hoping you could point out what I could be doing wrong?

My goal is to change the fill color of the bars on 'mouseover' and back to normal on 'mouseout' events.  I am following this simple example http://bost.ocks.org/mike/bar/2/#automatic. The only changes I've made is adding the event listeners and creating an element with the ReactFauxDOM.

The chart is rendering and the events are being triggered, as it is logging to the console, but the color is not changing.  I feel like there is probably a mistake in my implementation though I'm not sure?  Is there something I'm missing?

Any advice would be greatly appreciated.  Thanks and keep up the great work!

```javascript
import React from 'react';
import ReactFauxDOM from 'react-faux-dom';
import d3 from 'd3';

class TestChart extends React.Component {
    render() {
        var data = [4, 8, 15, 16, 23, 42];

        var width = 420;
        var barHeight = 20;

        var x = d3.scale.linear()
            .domain([0, d3.max(data)])
            .range([0, width]);

        var chart = d3.select(ReactFauxDOM.createElement('svg'))
            .attr('width', width)
            .attr('height', barHeight * data.length);

        var bar = chart.selectAll('g')
            .data(data)
          .enter().append('g')
            .attr('transform', function(d, i) { return 'translate(0,' + i * barHeight + ')'; });

        bar.append('rect')
            .attr('width', x)
            .attr('height', barHeight - 1)
            .on('mouseover', function(d) {
                d3.select(this).style('fill', 'green');
                console.log('over');
            })
            .on('mouseout', function(d) {
                d3.select(this).style('fill', 'steelblue');
                console.log('out');
            });

        bar.append('text')
            .attr('x', function(d) { return x(d) - 3; })
            .attr('y', barHeight / 2)
            .attr('dy', '.35em')
            .text(function(d) { return d; });

        return chart.node().toReact();
    }
};

export default TestChart;
```

**Comment by Olical** [comment]
That's easy enough to achieve and I've done something sort of similar by moving a tooltip around a graph as you mouse over points :) the trick is to move any state into the component state, remember that every time render is called all previous state is left. So you should actually do something like this. (this should probably be in the documentation because managing state is something people get a little confused by, it's probably because it's so different to normal D3 usage)

```javascript
        bar.append('rect')
            .attr('width', x)
            .attr('height', barHeight - 1)
            .style('fill', this.state.fillColour || 'red') // just using red as default, you should use get initial state or something...
            .on('mouseover', function(d) {
                this.setState({ fillColour: 'green' });
                console.log('over');
            })
            .on('mouseout', function(d) {
                this.setState({ fillColour: 'steelBlue' });
                console.log('out');
            });
```

Does that make sense? Instead of *mutating* which *will not work* you should update the component state and then use that new value on the next render. Feel free to ask if you have any further questions. Would it be okay for me to take this example and use it as documentation too?

**Comment by akash5474** [comment]
Thanks that totally makes sense.  I guess it was naive for me to assume that everything was supposed to be done in the d3 way.  I definitely prefer this way and after that insight I'm even happier to be using this library.

Adding an example to the documentation would be great.  I copied the one above straight from that link so I'm not sure if there would be any issue with using that.  You can use this one below if you like which has the desired effect of changing only the color of the bar currently being hovered over.  Thanks again, this library is really awesome

```javascript
import React from 'react';
import d3 from 'd3';
import ReactFauxDOM from 'react-faux-dom';

export default React.createClass({
    getInitialState() {
        return {
            data: d3.range(20).map(() => {
                // Integer from 5 to 20
                return Math.floor(Math.random() * (20 - 5 + 1)) + 5;
            }),
            hoverIdx: -1
        };
    },
    render() {
        const { data, hoverIdx } = this.state;

        const height = 400;
        const width = 600;
        const barWidth = width / data.length;

        const y = d3.scale.linear()
            .domain([0, d3.max(data)])
            .range([0, height - 10]);

        const chart = d3.select(ReactFauxDOM.createElement('svg'))
            .attr('width', width)
            .attr('height', height);

        const bar = chart.selectAll('g')
            .data(data)
            .enter().append('g')
            .attr('transform', (d, i) => `translate(${i * barWidth}, 0)`);

        bar.append('rect')
            .attr('y', y)
            .attr('height', d => height - y(d))
            .attr('width', barWidth - 1)
            .attr('fill', (d, i) => i === hoverIdx ? 'blue' : 'red')
            .on('mouseover', (d, i) => {
                this.setState({ hoverIdx: i });
                console.log('over', i);
            })
            .on('mouseleave', d => {
                this.setState({ hoverIdx: -1 });
                console.log('out');
            });

        return chart.node().toReact();
    }
});
```

**Comment by Olical** [comment]
I made [this example](http://lab.oli.me.uk/react-faux-dom-state/) based off of your requirement ([source](https://github.com/Olical/lab/blob/gh-pages/js/react-faux-dom-state/main.js)). I will be linking to that from the README :) I hope this has been helpful, closing now.
