### ISSUE TITLE
Support nesting of components before toReact()

### ISSUE THREAD

**Issue by r-tock** [Olical/react-faux-dom#31]
Right now if you need to create a line chart with an an X axis and y Axis,  a line and a tooltip.
You end up writing these all into one giant render function all writing these elements to the faux-dom using the d3 library. Every re-render will re-render the whole thing, specially when all you want is move the tooltip around.

Now lets say you want to componentize these. 
On the top level I want to create an svg with d3. Then add three sub-components xAxis, yAxis, Line and a Tooltip. I want the tooltip to render independently of the others because usually I want the re-render that on a mouse move. 

Proposal
Add an addChild(ReactComponent) support on the faux-dom element.
Have the method be able to specify a custom key so that we can make rendering on one subtree independent of the other.

Thoughts?

**Comment by Olical** [comment]
Hey there! I was under the impression that I had already added this, perhaps not. This [map over the children](https://github.com/Olical/react-faux-dom/blob/cfbd3aca0492cd67ac240146fb14ac5baee10f3b/src/Element.js#L275-L281) when we're actually creating the React elements should allow you to embed normal DOM or other React components. If that's not the case then maybe there's a bug?

Further evidence to suggest that you can already do this can be [found in the tests](https://github.com/Olical/react-faux-dom/blob/cfbd3aca0492cd67ac240146fb14ac5baee10f3b/test/react.js#L43-L55) too. So is this what you mean? Or maybe you know this exists and you're suggesting something slightly different?

Either way, I hope this is helpful :)

**Comment by r-tock** [comment]
Ah that is so much helpful, well its my fault i didn't go into the tests to find out about this. A table of supported features would help. 

This certainly helped me speed up render loop to sub 5ms in my dynamic hover solution where voronoi calculation and tooltip hovering is split from the rest of the chart. The performance is higher than 60fps that no one will realize this was done using react-faux-dom.

**Comment by Olical** [comment]
Beautiful! I'll make a note to document it.

**Comment by sungwoncho** [comment]
@r-tock I am trying to do something similar: a line chart with tooltips ([example](https://bl.ocks.org/d3noob/257c360b3650b9f0a52dd8257d7a2d73)). I implemented the chart, but I do not know where to begin to implement the tooltips with react-faux-dom. Could you share some tips or a snippet?

**Comment by sungwoncho** [comment]
This is what I ended up doing:

```js
...
    // Create a faux DOM for the chart
    const parent = ReactFauxDOM.createElement('div');
    const node = ReactFauxDOM.createElement('svg');
    parent.appendChild(node);
    parent.appendChild(
      <Tooltip
        left={tooltipLeft}
        top={tooltipTop}
        opacity={tooltipOpacity}
        data={tooltipData}
        key="chart-tooltip"
      />
    );

    // Manipulate the SVG node to draw the chart
    const svg = d3.select(node)
        .attr('width', width + margin.left + margin.right)
        .attr('height', height + margin.top + margin.bottom)
      .append('g')
        .attr('transform', `translate(${margin.left}, ${margin.top})`);

    svg.append('path')
      .data([data])
      .attr('class', 'line')
      .attr('d', valueline);

    svg.selectAll('dot')
      .data(data)
      .enter()
      .append('circle')
      .attr('r', 5)
      .attr('cx', (d) => x(d.date))
      .attr('cy', (d) => y(d.count))
      .on('mouseover', (d) => {
        this.setState({
          tooltipLeft: x(d.date) + margin.left,
          tooltipTop: y(d.count) + 2 * margin.top,
          tooltipOpacity: 0.9,
          tooltipData: d
        });
      })
      .on('mouseout', () => {
        this.setState({
          tooltipData: null
        });
      });
...
```
