### ISSUE TITLE
Returning Refs to react

### ISSUE THREAD

**Issue by Verikon** [Olical/react-faux-dom#33]
Consider;
```javascript
/*.. imports ..*/ 

class myClass extends React.Component {

  render( ) {
     this.container = ReactFauxDOM.createElement( 'svg' );
     return { this.rendition.toReact() }
  }

  rendition(){ 
   var myRect = d3.select( this.container ).append( 'rect' );
   ReactFauxDOM.toRef( myRect, 'rect' ); 
  }

  componentDidMount() {
    console.log( this.refs.rect )
  }

}
```
is it logical/sound from your perspective to provide a means such as the above so as to gain ReactJS refs from the faux dom when toReact is called?

**Comment by Olical** [comment]
Is it not already sort of supported? If you set a ref property in a tree, when you call `toReact` you can access those refs? Maybe I'm mistaken though. What is it you'd like to achieve? I thought refs were used almost solely for testing.

**Comment by Verikon** [comment]
As you've suggested, that works really well;

```javascript
rendition(){ 
 d3.select( this.container )
    .append( 'rect' )
    .attr( 'ref', 'rect' );
```

It was more a curiosity than anything else.

**Comment by Olical** [comment]
Oh cool :D yeah, most normal React things should work as you'd expect out of the box, including refs. I get a lot of questions about this sort of thing and most of the time I don't actually know then answer. I've just built a thin wrapper that passes most functionality through. Everything "just works" in the same way it normally would, just though a different interface.

Did this answer your question?

**Comment by Verikon** [comment]
Perfectly, it seems obvious when that penny drops - thank you for your time.

**Comment by Olical** [comment]
Excellent! Not a problem :smile:
