### ISSUE TITLE
Support for JSX?

### ISSUE THREAD

**Issue by canadaduane** [Olical/react-faux-dom#34]
I'm a bit surprised that the faux DOM createElement method doesn't support the same method signature as regular React.createElement:

```
ReactElement.createElement = function (type, config, children) {
```

ReactFauxDOM:
```
  createElement: function (nodeName) {
```

As a result, it appears it isn't possible to actually swap ReactFauxDOM in for React, and use JSX:

```
  render () {
    var _React = React;
    React = ReactFauxDOM;

    var result = (
      <div className="ViewsHistogram box">
        Hello
      </div>
    );

    React = _React;
    return result.toReact();
  }
```

(The `className` and `Hello` text are ignored by ReactFauxDOM).

Is there a reason for this? Why not use the same method signature, and get JSX support for free?

**Comment by Olical** [comment]
I wrote the API like this to follow the existing [document.createElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement) API. The goal was to follow the DOM API exactly, but just enough for it to work with D3 (for starters).

This was partially so you could avoid using JSX for something that D3 is quite good at, turning data into some form of complex document. (**d**ata **d**riven **d**ocuments). Turning JSX -> DOM -> JSX (essentially) is a strange round trip in my opinion.

This isn't supposed to be a rendering target for JSX, it's an *alternative* to JSX. JSX just compiles to function calls which create a React DOM. ReactFauxDOM is mutated then compiled to React DOM.

They're not really compatible with each other, they're options depending on how you are building your React DOM.

**Comment by canadaduane** [comment]
Got it. I misunderstood. Thank you!

**Comment by Olical** [comment]
No problem! Closing this now, I hope that helped :)

**Comment by zhenyulin** [comment]
```const axisGroup = Faux.createElement('g');
		axisGroup.setAttribute('class', className);
		axisGroup.setAttribute('transform', transform);
		const axisDom = select(axisGroup);
		const { xScale, tickSize, ticks } = this.props;
		const axis = axisBottom(xScale)
			.tickSize(tickSize)
			.ticks(ticks);
		axisDom.call(axis);
		return  axisDom.node().toReact();```

I'm getting patterns like this at the moment, so continuing on this topic, I'm thinking to get JSX to create the base element, while utilise D3 to create the children. The spread attributes feature has been specifically useful to clean up my code.

```const axisGroup = Faux.createElement(<g {...{className, transform}} />);
		const axisDom = select(axisGroup);
		const { xScale, tickSize, ticks } = this.props;
		const axis = axisBottom(xScale)
			.tickSize(tickSize)
			.ticks(ticks);
		axisDom.call(axis);
		return  axisDom.node().toReact();```
