### ISSUE TITLE
update dependancy to lodash 4

### ISSUE THREAD

**Issue by kidwm** [Olical/react-faux-dom#36]
But it also dropped IE 6-8 support.

**Comment by Olical** [comment]
I would be happy to do this but I'm not sure if others rely on that browser
support. Maybe we could just update all lodash dependencies to the latest
3.x.x, but 4 may be a bit of a risk.

**Comment by Olical** [comment]
I see three options here.

1. Upgrade lodash to v4, make the library only work in modern browsers (maybe bad)
2. Stick with v3 but update all to latest minor / patch
3. Replace everything with my own code that relies on ES5 features

I'm thinking option two or three, but using built ins probably has the same browser compatibility issues. Maybe people can just stick with the older version in that case.

react-faux-dom@3 could just be for modern browsers. If I'm going to break compatibility, I'd like to remove dependencies at the same time. The fewer the better!

I'm thinking option three with a major version bump would be best.

**Comment by kidwm** [comment]
Yeah, the fewer the better!

**Comment by Olical** [comment]
I'll be releasing this in v2.4.0. No more lodash dependencies :)
