### ISSUE TITLE
Implementation of mouseover function

### ISSUE THREAD

**Issue by Bonitis** [Olical/react-faux-dom#44]
I am trying to implement a tooltip on a line chart that will typically have around 2700 data points. I set it up by starting with the solution from #29. The code below has the state change where instead of a color change, I am updating the opacity from 0 to 1. Once there are lots of data points, it becomes horribly slow. Is there a better way to implement mouseover behavior so that there will not be a huge lag as the mouse moves across the chart?

```
svg.selectAll('.bar')
      .data(data)
      .enter().append('rect')
      .attr('class', 'annotation-bar')
      .attr('x', function(d) { return x(d.Time); })
      .attr('y', margin.top)
      .attr('height', height - margin.top)
      .attr('width', '10px')
      .attr('opacity', 0)
      .on('mouseover', function(d) {
          that.setState({
            xLabel: x(d.Time) + margin.left,
            yLabel: y(d.HeartRate) + margin.top,
            labelHR: d.HeartRate,
            labelTime: d.Time,
            opacity: '1.0'
          });
      })
      .on('mouseout', function(d) {
        that.setState({
          xLabel: 0,
          yLabel: 0,
          labelHR: '',
          labelTime: '',
          opacity: '0.0'
        });
      }
    );
```

**Comment by Olical** [comment]
The best way to do this is make the thing that changes a child of the main chart. This can also be a React component. Then the child can change without the parent having to re-render. Basically you have to work to avoid re-renders of the entire chart.

It's the same as building a HUGE JSX structure in your render call of some component. It'll get slower as it grows. That's one of the reasons why we divide our application into smaller sub-components. The same applies to charts within the React DOM. You should split out small things that change within a larger whole.

You can compose faux DOM inside React DOM and React DOM in faux DOM pretty easily, which makes it fairly simple to compose.

**Comment by Bonitis** [comment]
Ok cool, that makes sense. Thanks!

**Comment by BMPMS** [comment]
Hi @Olical ,

I'm a d3 developer new to React and I'm having trouble translating your answer.  

Is there any chance you could adapt my example so that  <div className="tooltip"></div> is 
a child of my Bar_Chart component.

I've used your sandbox example as a starting point so hopefully easy for one who knows how!
