### ISSUE TITLE
weird string in style attribute

### ISSUE THREAD

**Issue by kidwm** [Olical/react-faux-dom#5]
I just use the example from README.md.

![foax-dom](https://cloud.githubusercontent.com/assets/822446/9955111/00feee10-5e21-11e5-98cc-76b02d10ad04.png)
```js
var Graph = React.createClass({
	propTypes: {
		data: React.PropTypes.arrayOf(React.PropTypes.number)
	},
	render: function () {
		var chart = d3.select(ReactFauxDOM.createElement('svg'));
		chart
			.selectAll('g')
			.data(this.props.data)
			.enter().append('g')
			.classed('bar', true)
			.attr('width', function (d, i) {
				return d * 10
			})
			.text((d) => d);
		return chart.node().toReact();
	}
});
```

**Comment by Olical** [comment]
That's odd but I think I know what's causing that. I'll fix it tonight (around 8:00pm GMT), I apologise for any inconvenience! For now you could try setting style to an empty object or something, it's basically the functions I defined on the `style` object through `Object.defineProperty`. [Here's the source]https://github.com/Olical/react-faux-dom/blob/436dd4c84cdbc3826f93edbb9f1f2c42b469d353/src/Element.js#L12-L26). Not quite sure why they leak in this case though.

What's your React version? That may well have something to do with it. I probably broke something when adding support for style strings :fearful:

**Comment by kidwm** [comment]
I use it with React 0.13.3, thank you!
