### ISSUE TITLE
Fake DOM element has no getBoundingClientRect method

### ISSUE THREAD

**Issue by alexyuly** [Olical/react-faux-dom#50]
To reproduce, select a react-faux-dom `div` with [D3](https://github.com/d3/d3), append an `svg`, and then call a [behavior](https://github.com/d3/d3/wiki/Behaviors), e.g.:

    import d3 from 'd3';
    import ReactDOM from 'react-dom';
    import { createElement } from 'react-faux-dom';

    const target = createElement('div');
    d3.select(target).append('svg').call(d3.behavior.drag());
    ReactDOM.render(target.toReact(), document.getElementById('render-target'));

The browser throws an error when you click/drag the `svg` element:
`d3.js: Uncaught TypeError: x.getBoundingClientRect is not a function`

Similar code using a real DOM element throws no error:

    const target = document.createElement('div');
    d3.select(target).append('svg').call(d3.behavior.drag());
    document.getElementById('render-target').appendChild(target);

The desired behavior is that the fake element supports `getBoundingClientRect`, like a real DOM element.

**Comment by stocksp** [comment]
adding getBoundingClientRect to the Element api  would be GREAT as its all that's keeping a bunch of ported code from running!!

**Comment by jurgob** [comment]
+1

**Comment by Olical** [comment]
All thanks to @alexyuly, v2.7.0 contains this feature. I hope everything works well for you all, feel free to open issues if you encounter... issues.

**Comment by alexyuly** [comment]
Thanks for merging @Olical!
