### ISSUE TITLE
Made with React-Faux-DOM

### ISSUE THREAD

**Issue by kennetpostigo** [Olical/react-faux-dom#51]
Hey, just opened sourced a library that uses `react-faux-dom`, check it out 😄
[component-kit](https://github.com/kennetpostigo/component-kit)

Also theres a link there to show you a dashboard.

**Comment by Olical** [comment]
Nice! I hope it's working well for you! Looks pretty slick :smile:

Added a link in the readme https://github.com/Olical/react-faux-dom/commit/5b64976ddcb1c89d8284d6ac485dc764a853fcbd

**Comment by kennetpostigo** [comment]
It is thanks so much @Olical !

**Comment by kennetpostigo** [comment]
Tomorrow will add the composition experiences in the wiki
