### ISSUE TITLE
D3 v4.0.0

### ISSUE THREAD

**Issue by Olical** [Olical/react-faux-dom#54]
So [D3 v4.0.0](https://github.com/d3/d3/releases/v4.0.0) is out now which includes a number of changes, including ES6 modules so you don't have to pull in everything anymore.

I'm wondering if they changed the use of the DOM significantly though, which would not work with ReactFauxDOM without modification. I haven't tried it yet and *maybe* it'll **Just Work<sup>TM</sup>**.

Let me know here if you encounter blocking issues. Then if anyone wants to help shim those new methods that'd be amazing. :smile:

**Comment by c0zzy** [comment]
Hi, the new v4 seems a lot different to me. I haven't figured out how to make it work with react-faux-dom. Have someone tried something? A minimal example how to put it together would be nice.

**Comment by funkjunky** [comment]
I got as far as the data function, then i get "Cannot read property 'ownerDocument' of null"
Something well need to be changed internally.

I'm a newbie with ES6, D3, and redux, but I'll try and take a stab tomorrow evening if this hasn't been figured out by then.

I could just downgrade, but v4 seems so much nicer than v3 syntactically.

**Comment by funkjunky** [comment]
I got rid of the error by using the constructor instead of createElement and passing the second argument 'parent'. I just passed another faux element =P Basically to appease the system.

Nothing is showing yet though...

**Comment by sebinsua** [comment]
I'm also contemplating upgrading here.

Relating to @funkjunky's comment, [`ownerDocument`](https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument) seems to be [defined here?](https://github.com/Olical/react-faux-dom/blob/master/lib/ReactFauxDOM.js#L26) I wonder what caused `Element` to be `null`ed...

**Comment by Olical** [comment]
Since @sebinsua has gone ahead and verified this with their PR, I'm pretty happy to close this. If anything else comes up it can be a separate issue, it looks like D3 v4 didn't break everything. :tada:
