### ISSUE TITLE
Typescript and mixins

### ISSUE THREAD

**Issue by MichaelBitard** [Olical/react-faux-dom#57]
Hi,

I'm trying to play with D3 and react so I assume this is the place to be.

I have a typescripted project and I don't know how to make everything work.

I was able to make this example (https://github.com/Olical/lab/blob/gh-pages/js/react-faux-dom-state/main.js) work with some minor tweaks (ie: I extracted the variable `ReactFauxDOM.createElement('svg')` and called `toReact()` on it instead of `svg.node().toReact()`

But when I tried another simple animated example (http://bl.ocks.org/jose187/4733747) I ended with a non animated graph really ugly. So I started playing with componentDidMount but I wasn't able to add the svg to the already existing dom.

The source code of my class is here (https://github.com/MichaelBitard/react-blank-project/blob/try_animate/src/components/Topology/Topology.tsx), is there something obvious that I did wrong?

**Comment by MichaelBitard** [comment]
Mmmh, I found a solution but without react-faux-dom, I'm not sur this is the good way to go.

In my render:

    public render() {
        return (<div id="graph" style={{width:"1250px", height:"380px"}}></div>)
    }

and in componentDidMount:

    public componentDidMount() {
        var graph = document.getElementById("graph");

        var svg = D3.select(graph).append('svg')
            .attr({
                width: "1250",
                height: "380"
            });
      .
      .
      .
    }

**Comment by Olical** [comment]
D3 mutates the DOM to animate it, this does not work in React since everything is immutable and thrown away after each render. You can use mixins to get around this (as shown in [the documentation](https://github.com/Olical/react-faux-dom/blob/master/DOCUMENTATION.md#react-component-mixins)). The only way around this without some sort of mixin to help you is to use a React animation library, you can feed those values as they change over time into your chart to animate it manually.

**Comment by MichaelBitard** [comment]
Ok, That was my main issue, I don't know how to use your mixins with Typescript and I wasn't able to find any examples.

**Comment by Olical** [comment]
I'm really not sure about TypeScript integration, I've never used it or really looked at it. You'll probably need to write your own definitions, I don't know how that sort of thing works.

If you use a React animation library you can not use any D3 transforms. If you want to use D3 animation you need to either use the mixins or break out of the React tree as you showed in your second example.

Honestly I'd recommend you go down the latter route. Just skip out of React and ignore react-faux-dom. Then you can use any interaction / animations you want as well as have a slightly easier integration with TypeScript.

For your use case, this doesn't seem like the right tool. It's good for simple things, but begins to breakdown in these cases without compromises.

**Comment by MichaelBitard** [comment]
Thanks a lot for your answers, I think i'll do what you said!
