### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Olical** [Olical/react-faux-dom#6]
I need to document the full extent of the API with examples. More importantly, I need to document adding features that are missing.

**Comment by Olical** [comment]
Anyone have any opinions or wishes around this? Should I use GitHub wiki? Just have a `DOCUMENTATION.md` / put it in `README.md`? Keeping it in a file is my preference. What do you want documented, API / usage examples?

It'd probably end up similar to my other project, thoughts on that? https://github.com/Olical/EventEmitter

**Comment by wuxianliang** [comment]
EventEmitter's documents are good! Probably, we will use react-faux-dom for reusing D3 codes. So one concept proof example with some hints on which parts can not work just by drop in is good enough for me.

**Comment by Olical** [comment]
I'm going to integrate with inch-ci http://inch-ci.org/github/Olical/react-faux-dom?pending_build=113610 for API documentation but will also add examples to a README / wiki.
