### ISSUE TITLE
querySelectorAll is not a function

### ISSUE THREAD

**Issue by BillyZac** [Olical/react-faux-dom#60]
I get an error when I run this within a React component:

```
d3.select(‘.container’)
  .selectAll(‘div.dataPoint’)
  .data(incomingData)
  .enter()
  .append(‘div’)
  .attr(‘class’, ‘dataPoint’)
  .html(function(d) { return d.label })
```

The error: 

```
bundle.js:7360 Uncaught TypeError: this.querySelectorAll is not a function
```

I'm using D3 v4.1.1

**Comment by Olical** [comment]
Is this the full code example? Where are you referencing a faux DOM node? That `d3.select` looks like a global query to me, which has nothing to do with `react-faux-dom`.

**Comment by Olical** [comment]
Without any more context I'm not sure if I'm going to be able to help here. From your snippet it looks like you're not even using a faux DOM node. If this isn't an issue any more would you be okay to close this issue?

**Comment by Olical** [comment]
Going to close this for now, I'm not sure if I can help. It doesn't seem like an issue with `react-faux-dom`.
