### ISSUE TITLE
app.js:7851Uncaught TypeError: Cannot read property 'select' of undefined

### ISSUE THREAD

**Issue by aleksandrenko** [Olical/react-faux-dom#62]
import './style.less';

import React from 'react';

import d3 from 'd3';
import ReactFauxDOM from 'react-faux-dom';

const Component = React.createClass({
  render: function () {
    const svg = ReactFauxDOM.createElement('svg');

    d3.select(svg)
        .attr({
          width: 300,
          height: 300
        })
        .append('rect')
        .attr({
          width: 300,
          height: 300,
          fill: 'green'
        });

    return svg.toReact()
  }
});

export default Component;

**Comment by OlivierCo** [comment]
hey what was your problem? I'm facing the same problem right now. Any chance to have an help from you?

**Comment by ashnur** [comment]
https://xkcd.com/979/
