### ISSUE TITLE
Improve docs: ES6 usage example

### ISSUE THREAD

**Issue by GeorgeStrakhov** [Olical/react-faux-dom#64]
First, thanks for great work!

Second, I followed the [example](https://github.com/Olical/react-faux-dom/blob/d8104163791be2e0b66e745ec85c84ca2005c448/examples/animate-d3-with-mixin/index.js) and struggled for a few minutes to get this to work in ES6 before I realising that I needed to do `import * as d3 from 'd3'` instead of `import d3 from 'd3', as per [this thread](https://github.com/d3/d3/issues/2921).

@Olical, do you have any plans to update the docs to include some ES6 usage example, or should I do a simple PR with an ES6 example?

**Comment by Olical** [comment]
Ah, that's a sneaky one that caught me out too. Not the first time I've been angry at the JavaScript module system (or JavaScript in general). It'd definitely be worth documenting it, even though D3 isn't a hard requirement for this project it's something that will catch people out again and again.

Maybe add a section to the readme just after installation that shows ES5 and ES6 import styles with the D3 caveat. Maybe even a script tag for the CDN version too. One quirk about the CDN file (which I don't use, some people requested it, I think you should depend on it and build it into your main script) is the name it's exported with. It's accessed by `window['react-faux-dom']` not `window.ReactFauxDOM` as you'd expect.

Could be worth mentioning that too. I can do it but if you had some time and wanted to write up a little readme section I'd be happy to merge it :smile:

**Comment by GeorgeStrakhov** [comment]
I am new to all this, but here is an attempt: #65 .
I only covered basic D3+ES6 usage, and not other issues you mentioned.
