### ISSUE TITLE
'toReact' should not set default React 'key'

### ISSUE THREAD

**Issue by FunkMonkey** [Olical/react-faux-dom#67]
Currently, `toReact` will set [`faux-dom-0`](https://github.com/Olical/react-faux-dom/blob/master/lib/Element.js#L256) as the default `key` on the react element, when no `index` was provided, leading to `children with same key` issues - at least when creating multiple elements without `index` and passing them as an array. There are situations where it is perfectly fine not to set a key, as React will simply use the array index or similar. 

I thus propose to either:
- not set the `key` at all attribute if `index` was not provided
- or to set a `uuid` as the `key` to prevent collisions (again if `index` was not provided)

What do you think?

Great library btw. Thanks a lot.

**Comment by Olical** [comment]
This sounds promising. I would imagine my default key stuff is actually slowing react down in places. I'll have a think and get back to you. If you want to propose anything (not saying you have to!) be my guest. Code is nice to discuss :) or even just a test.

I hope it has helped you!

**Comment by FunkMonkey** [comment]
How about in [Element.js#L259](https://github.com/Olical/react-faux-dom/blob/master/lib/Element.js#L259) instead of 

```js
if (isUndefined(props.key)) {
    props.key = uniqueKey()
}
```
we do

```js
// remove: index = index || 0 in line 249 and ...
if (isUndefined(props.key) && !isUndefined(index) ) {
    props.key = uniqueKey()
}
```
?

Not sure if prepending `faux-dom-` in `uniqueKey` breaks expectations. Maybe that should be changed, too?

**Comment by Olical** [comment]
So this has been open for a long time now, I apologise. I've lost sight of the original issue, but I would like to incorporate the little refactor in this closed PR for when you only have one child https://github.com/Olical/react-faux-dom/pull/74/files

I would like to leave the key system untouched, I don't like the global state of #73 (sorry :cry:). As far as I know, everything works fine but the single element fix is valid and people just need to set a key if they put two faux DOM elements next to each other.

I won't just close this now, I'll wait for replies (if any). I never felt like there was a concrete issue here to solve, just unanswered questions. Maybe more documentation is the answer.
