### ISSUE TITLE
Add `install()` function to allow globals to be modified?

### ISSUE THREAD

**Issue by dchambers** [Olical/react-faux-dom#70]
Hi @Olical, I was thinking about raising a pull-request for D3 to prevent it using the `window` or `document` globals, and instead using code like `node.ownerDocument` and `node.ownerDocument.defaultView`, but this just seems wrong since it's perfectly valid for D3 to do that, and it shouldn't have to start using awkward syntax for the sake of 'react-faux-dom'.

Instead, it seems like the correct thing to do would be to add an `install()` method to 'react-faux-dom' that updated these global objects so that they behave correctly. Apps could then invoke this method before using D3, or any libraries that use D3.

What do you think? Does this make sense, and if so should I try to create a pull-request for this?

**Comment by Olical** [comment]
This would involve mutating the global object and monkey patching things, right? I'm not too keen on the idea of that, it's a library and I'd rather it stayed self contained. I think we should propose the change to D3 if it doesn't affect D3 but will fix this bug.

Yes it's valid to do it both ways, but I wouldn't want to be running a function that hooks into globals. Especially when I'm using React and want everything to be as functional and as pure as possible.

**Comment by dchambers** [comment]
Okay, I'll propose a change on the D3 project...

To be clear though, the monkey patching would never be done by the library because it would be wrong for a library to do that on its own behalf; instead, apps would choose to do the monkey patching (by invoking an `installI()` function) as it's okay for apps to do that kind of thing.

**Comment by dchambers** [comment]
Hmm, I just started looking at the current D3 code and it looks like it's already been done in D3 4.x, but it's hard to be sure because the code is spread around in a lot of different sub-projects. For example, this [line of code here](https://github.com/d3/d3-selection/blob/af700ca87846833ba3a21135efecc5c95828e391/src/selection/style.js#L30) is using a [`defaultView`](https://github.com/d3/d3-selection/blob/af700ca87846833ba3a21135efecc5c95828e391/src/selection/style.js#L1) object that's [exported here](https://github.com/d3/d3-selection/blob/af700ca87846833ba3a21135efecc5c95828e391/src/window.js#L1), and which works in exactly the way we'd need it to work.

@mbostock, would love to get your feedback on this issue. Does D3 now always grab `window` & `document` references like this?

**Comment by dchambers** [comment]
Okay, looks like this was fixed in D3 quite a long time ago, and upgrading to the latest 3.X release of D3 fixed this for me. I'd ended up trying older and older versions of D3 to get the [NVD3 demos](http://nvd3.org/examples/index.html) working, before finding the [new NVD3 demo page](http://nvd3-community.github.io/nvd3/examples/site.html) that works correctly with D3 3.X, and using that example code instead.
