### ISSUE TITLE
Not able to set Children

### ISSUE THREAD

**Issue by JeroenBe** [Olical/react-faux-dom#76]
# Not able to set Children

According to the documentation, there are several ways to set children to a `ReactFauxDOM.Element`, also, children can be either a `ReactFauxDOM.Element` or a `React.Component`. Yet, this isn't working for me.
### What am I trying to accomplish?

I'm using D3 (v4) to visualise a force layout of nodes, next to D3, I'm also using react-bootstrap as they have some handy components for Tooltips. For such a tooltip to work, you need to specify the `react-bootstrap` component as the parent of the component you'd like a tooltip over. As such, I need a way to insert children in the `ReactFauxDOM` structure, in order to set their children. 

Here's the code I have so far, that I know works:

``` JavaScript
const faux_svg = new ReactFauxDOM.Element('svg')
faux_svg.appendChild(new ReactFauxDOM.Element('g'))
```

This generates something like this:

``` HTML
<svg>
  <g></g>
</svg>
```

Now, in stead of a `<g></g>` element, I need this `react-bootstrap` component:

``` JavaScript
const faux_svg = new ReactFauxDOM.Element('svg')
faux_svg.appendChild(React.createElement('OverlayTrigger'))
```

This doesn't work, no errors are thrown, it just doesn't work. 
Some alternatives I tried:

``` JavaScript
faux_svg.appendChild(React.createElement('g'))

faux_svg.appendChild(<OverlayTrigger />)

const ot = <OverlayTrigger />
faux_svg.appendChild(ot)

const ot = new ReactFauxDOM.Element('g', faux_svg) // even calling children this way, doesn't work
```

I'm not sure what I'm doing wrong here. Hope someone can point me in the right direction.

PS: Love the library!

**Comment by Olical** [comment]
Hm, there's [this test](https://github.com/Olical/react-faux-dom/blob/d3d5cb74dfad60ff22dc16f0d945d76ce97af443/test/react.js#L43-L55) for it that works fine. You may also encounter issues further down the road since force directed graphs require lots of animations and the mutation of the DOM if I'm not mistaken. You'll probably have to use the animation mixins, of which I have little experience I'm afraid.

By "doesn't work", do you mean it is not rendered into the DOM?

**Comment by JeroenBe** [comment]
Thanks for the reply!

Right now I have the graphs working, all that needs to happen is adding a Tooltip to the elements in the graph. I have done this before, only I subdivided my graph into multiple components. Since I'm working with the `d3-force` library, this is rather hard + like you said, expensive. 

In my case "doesn't work" has multiple meanings. Or it's not rendered, or the component crashes. All my tries that include initialising the child components like this: `new ReactFauxDOM.Element('g', parentElement)` wont render. Everything else crashes.

Converting a React component to a ReactFauxDOM element might help me out (not sure if this is possible), but I'd rather use your library as documented.

**Comment by Olical** [comment]
Sorry about not getting back to you, completely forgot :cry: 

I'd imagine you'd already solved this or moved on by now, so I'm going to close this. Will re-open if this issue appears to be more wide spread.

I think you were just trying to use very animated and mutation driven code, which doesn't really work with this. Great for static things, not so great for smooth, force based graphs. For that, step out of the React tree like normal.

I hope you solved your issues! :smile:
