### ISSUE TITLE
ES6 Classes

### ISSUE THREAD

**Issue by caleb272** [Olical/react-faux-dom#77]
Is there a way to use the mixins in an ES6 class if not is there an update coming that works with ES6 classes.

**Comment by Olical** [comment]
I'm not sure, that depends on if React lets you use mixins with ES6 classes or not. If it doesn't, then no, I'm  afraid not. And I have no plans to add support at the moment.

**Comment by palnes** [comment]
Starting with React 16, `React.createClass()` will no longer be part of the core React package. Mixins are also [considered harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html) by the core React team. An option could be to reimplement the mixins as [Higher Order Components](https://facebook.github.io/react/docs/higher-order-components.html) (HoC)

**Comment by Olical** [comment]
Oh, that's annoying. I can't promise I'll get around to keeping up with any of that in a timely manner at the moment I'm afraid.

**Comment by tibotiber** [comment]
@caleb272 @palnes version 4.0.0 has just been published and supports ES6 classes with an HOC :)
