### ISSUE TITLE
Images do not show up

### ISSUE THREAD

**Issue by findcongwang** [Olical/react-faux-dom#78]
I'm trying to recreate a simple JSFiddle: http://jsfiddle.net/am8ZB/
Below is my component, I used the same code in render, but with FauxDOM for creating the svg.
No luck with using png files either.

```
import React from 'react'
import * as d3 from 'd3'
import ReactFauxDOM from 'react-faux-dom'

class D3SLDiagram extends React.Component {

  constructor(props) {
    super(props)
    this.state = {}
  }

  render () {
    var width = 800, height = 800;

    var svg = d3.select(ReactFauxDOM.createElement('svg'))
        .attr("width", width)
        .attr("height", height);

    var g = svg.append("g");

    var img = g.append("svg:image")
        .attr("xlink:href", "http://www.clker.com/cliparts/1/4/5/a/1331068897296558865Sitting%20Racoon.svg")
        .attr("width", 200)
        .attr("height", 200)
        .attr("x", 228)
        .attr("y",53);

    return (
      <div className='network D3SLDiagram'>
        {svg.node().toReact()}
      </div>
    )
  }
}

export default D3SLDiagram
```

Result:
![ss](https://cloud.githubusercontent.com/assets/1127053/21152315/c1931c8e-c133-11e6-8a00-2522e8b91d93.png)

I'm totally stuck, any help would be appreciated, thanks!

**Comment by Olical** [comment]
That's really strange, at first I thought it was the `xlink:href` attribute tripping it up because of the `:`. But the `href` attribute made it into the real DOM. Can you see the image being requested in your inspector? If so, maybe it's simply a styling thing?

**Comment by Olical** [comment]
Going to close this with the assumption that you worked it out or moved onto another tool. I see no reason why it wouldn't work though, the library doesn't care about what's inside (be that an image or some text), it's just passing stuff along.
