### ISSUE TITLE
Wrapping text

### ISSUE THREAD

**Issue by ammmze** [Olical/react-faux-dom#80]
Any idea how I would go about rendering text that wraps at a certain width using `react-faux-dom`? I tried borrowing the wrap method found [here](https://bl.ocks.org/mbostock/7555321), however, the `getComputedTextLength` does not exist (which of course makes sense since, its not mentioned in the API). Got any ideas for how I can wrap arbitrary text using this?

**Comment by Olical** [comment]
You can't measure text until it's rendered into the DOM, so adding measuring tools doesn't make sense. I'd say render it into D3 then measure. The only way you know how big something is on a web browser is by actually rendering it then measuring somehow. It will also give you a different size based on OS and browser because fonts are weird.

**Comment by ammmze** [comment]
Thanks ... I figured that would be your answer. Here's an excerpt of what I used.

Set a ref to the div surrounding my d3 component
```javascript
render: function () {
    return <div ref={(r) => (this.graph = r)} className='graph'>
        {this.state.chart}
    </div>
},
```

create method named wrapText that takes a d3 selection and a width. it will then take the text and split it up into individual `tspan`'s within the `<text>`. On subsequent runs (i.e. in animations) it will skip the split up since it detects the the `<text>` element has children. Currently it just assumes they are `tspan`'s. It also assumes the width has not changed.
```javascript
wrapText: function(text, width) {
    text.each(function () {
        var text       = d3.select(this);
        if (text.node().children.length > 0) {
            // assuming its already split up
            return;
        }
        var words      = text.text().split(/\s+/).reverse(),
            word,
            line       = [],
            lineNumber = 0,
            lineHeight = 1.1, // ems
            y          = text.attr("y") || 0,
            dy         = parseFloat(text.attr("dy") || 0),
            tspan      = text.text(null).append("tspan").attr("x", 0).attr("y", y).attr("dy", dy + "em");

        while (word = words.pop()) {
            line.push(word);
            tspan.text(line.join(" "));
            if (tspan.node().getComputedTextLength() > width) {
                line.pop();
                tspan.text(line.join(" "));
                line  = [word];
                tspan = text.append("tspan").attr("x", 0).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word);
            }
        }
    });
}
```

on component update select the labels that potentially need wrapping (in my case it was a all the node labels...they need to appear inside a rectangle) and call the wrapText method.
```javascript
componentDidUpdate: function () {
    this.wrapText(d3.select(this.graph).selectAll('.node .label'), this.props.rectWidth);
},
```
