### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by 1simonfish** [Olical/react-faux-dom#81]
I downloaded v3.0.0 of this project, then ran `make`. All the tests pass, but there's nothing in ./dist and I get a bunch of NPM warnings:

```
npm WARN bastion@1.8.0 requires a peer of elm-hot-loader@* but none was installed.
npm WARN bastion@1.8.0 requires a peer of elm-webpack-loader@* but none was installed.
npm WARN bastion@1.8.0 requires a peer of react-hot-loader@* but none was installed.
npm WARN babel-loader@6.2.10 requires a peer of babel-core@^6.0.0 but none was installed.
```
Any suggestions?

**Comment by Olical** [comment]
This looks like an issue with bastion, a build tool I made a while back to make dealing with npm/babel a little less painful. It turns out that it can still be painful.

Newer versions of npm break many assumptions I had, I will have to change the toolchain again and just deprecate bastion.
