### ISSUE TITLE
just dropping a note to say thanks!

### ISSUE THREAD

**Issue by peter-mouland** [Olical/react-faux-dom#83]
found this repo (after react-d3; which was clearly a non-starter) and instantly worked as described.  Love it when then happens. cheers

**Comment by Olical** [comment]
Well thank you for the thanks :smile:

I hope it's working well for you, I presume you have a stateless usecase for it? Most of the issues I get are people trying to do mutative D3 things and still trying to use this. In the case of D3 based mutation / animations, the old style of dropping out of React-land for a little while is basically always the answer.

**Comment by peter-mouland** [comment]
cool, yeah the chart is stateless... i'm able to control state with a parent component as i don't have to worry about animations at the moment.. simple use case


<img width="846" alt="screen shot 2017-02-24 at 10 37 26" src="https://cloud.githubusercontent.com/assets/1727939/23300400/44b8598a-fa7d-11e6-81cc-d1d563e13565.png">
