### ISSUE TITLE
Make events work like the normal DOM

### ISSUE THREAD

**Issue by Olical** [Olical/react-faux-dom#9]
This involves the following changes which should help with things like #4.

 * [x] Calling `addEventListener` multiple times should allow you to add multiple listeners.
 * [x] Events such as mouse events should pass the native event through, not the synthetic React event.

## On listeners...

Right now I have a dumb approach which removes the previous listener and replaces it because I'm just setting `props.onClick`, for example. This needs to basically delegate to some event system that allows you to add or remove multiple listeners. An abstraction on top of Reacts event system to make it behave like the DOM.

## On event objects...

This should allow things like `d3.mouse` to work, right now it completely fails, you have to hit `d3.event` and work it out yourself.

**Comment by KeitIG** [comment]
Give that man à cookie...

Thanks a lot !

**Comment by Olical** [comment]
No problem :D I needed something to do on this five hour long train ride!

**Comment by tristanguigue** [comment]
I can't seem to get `d3.mouse` to work still. It throws a `TypeError: container.getBoundingClientRect is not a function`

Using this (simplified) example:

    let container = d3.select(ReactFauxDOM.createElement('svg'));
    container.selectAll('g')
        .data(data)
      .enter().append('g')
        .append('path')
        .attr('d', function(d) {return line(d.values);})
        .on('mouseover', function() {
            let pos = d3.mouse(this) // throws an error
        });

Any reason why this is?

**Comment by alexyuly** [comment]
@tristanguigue +1. I'm getting the same error (`container.getBoundingClientRect is not a function`) calling a D3 zoom behavior on an SVG element appended to a `<div>` created with react-faux-dom, like so (simplified for clarity):

    d3.select(createElement('div'))
      .append('svg')
        .call(d3.behavior.zoom().on('zoom', () => { ... })
        .append('g');

Perhaps I am missing something.

**Comment by Olical** [comment]
Interesting, would you like to open another issue with some steps to reproduce? Once we have tests for it, it'll be a lot easier.

**Comment by sungwoncho** [comment]
@Olical I think I found a related issue. Please see #66.
