### ISSUE TITLE
Medium post about react-faux-dom

### ISSUE THREAD

**Issue by tibotiber** [Olical/react-faux-dom#92]
Just wanted to drop here that I have published a [medium post](https://medium.com/@tibotiber/react-d3-js-balancing-performance-developer-experience-4da35f912484) about react-faux-dom, comparing it with alternatives and suggesting a few performance tricks. Feel free to provide feedback, share it, etc. If you think it is valuable, we can also add a link in the README (?).

@Olical: I mentioned you directly, so please check and let me know if you need me to make any changes.

I will probably try to reach out to authors of the posts that I mentioned to get their views as well. Hopefully, it can help to promote this amazing lib :).

**Comment by Olical** [comment]
That's really cool! An excellent post, I think it'll be great to add to the readme.
